In [2]:
import numpy as np                

In [3]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [129]:
my_array = np.array(["a", "t", "c",52, '7'])
my_array

array(['a', 't', 'c', '52', '7'], dtype='<U11')

In [119]:
my_array2 = np.array([[1, 2, 3], [5, 6, 7]])

In [50]:
my_array2.dtype

dtype('int32')

In [17]:
my_array2*2

array([[ 2,  4,  6],
       [10, 12, 14]])

In [18]:
my_array3 = np.array([[2, 5, 7], [9, 3, 5]])

In [19]:
my_array2*my_array3

array([[ 2, 10, 21],
       [45, 18, 35]])

In [74]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [75]:
np.arange(1, 10, 3)

array([1, 4, 7])

array(['1.0', '5.5', '10.0'], dtype='<U32')

In [76]:
my_array3.shape

(2, 3)

In [78]:
my_array3

array([[2, 5, 7],
       [9, 3, 5]])

In [80]:
my_array3.reshape((2, 2))

ValueError: cannot reshape array of size 6 into shape (2,2)

In [79]:
my_array3.T

array([[2, 9],
       [5, 3],
       [7, 5]])

In [91]:
w = np.array([1,4,5., 522])

In [92]:
w.dtype

dtype('float64')

In [96]:
lrg_array = np.linspace(1, 100, 80, dtype = np.int32)

In [97]:
lrg_array

array([  1,   2,   3,   4,   6,   7,   8,   9,  11,  12,  13,  14,  16,
        17,  18,  19,  21,  22,  23,  24,  26,  27,  28,  29,  31,  32,
        33,  34,  36,  37,  38,  39,  41,  42,  43,  44,  46,  47,  48,
        49,  51,  52,  53,  54,  56,  57,  58,  59,  61,  62,  63,  64,
        66,  67,  68,  69,  71,  72,  73,  74,  76,  77,  78,  79,  81,
        82,  83,  84,  86,  87,  88,  89,  91,  92,  93,  94,  96,  97,
        98, 100])

In [100]:
lrg_array = lrg_array.reshape(8, 10)

In [101]:
lrg_array

array([[  1,   2,   3,   4,   6,   7,   8,   9,  11,  12],
       [ 13,  14,  16,  17,  18,  19,  21,  22,  23,  24],
       [ 26,  27,  28,  29,  31,  32,  33,  34,  36,  37],
       [ 38,  39,  41,  42,  43,  44,  46,  47,  48,  49],
       [ 51,  52,  53,  54,  56,  57,  58,  59,  61,  62],
       [ 63,  64,  66,  67,  68,  69,  71,  72,  73,  74],
       [ 76,  77,  78,  79,  81,  82,  83,  84,  86,  87],
       [ 88,  89,  91,  92,  93,  94,  96,  97,  98, 100]])

In [102]:
lrg_array[1:,1:]

array([[ 14,  16,  17,  18,  19,  21,  22,  23,  24],
       [ 27,  28,  29,  31,  32,  33,  34,  36,  37],
       [ 39,  41,  42,  43,  44,  46,  47,  48,  49],
       [ 52,  53,  54,  56,  57,  58,  59,  61,  62],
       [ 64,  66,  67,  68,  69,  71,  72,  73,  74],
       [ 77,  78,  79,  81,  82,  83,  84,  86,  87],
       [ 89,  91,  92,  93,  94,  96,  97,  98, 100]])

In [103]:
lrg_array[:3, :3]

array([[ 1,  2,  3],
       [13, 14, 16],
       [26, 27, 28]])

In [105]:
lrg_array[:, ::2]

array([[ 1,  3,  6,  8, 11],
       [13, 16, 18, 21, 23],
       [26, 28, 31, 33, 36],
       [38, 41, 43, 46, 48],
       [51, 53, 56, 58, 61],
       [63, 66, 68, 71, 73],
       [76, 78, 81, 83, 86],
       [88, 91, 93, 96, 98]])

In [106]:
lrg_array[:, 1::2]

array([[  2,   4,   7,   9,  12],
       [ 14,  17,  19,  22,  24],
       [ 27,  29,  32,  34,  37],
       [ 39,  42,  44,  47,  49],
       [ 52,  54,  57,  59,  62],
       [ 64,  67,  69,  72,  74],
       [ 77,  79,  82,  84,  87],
       [ 89,  92,  94,  97, 100]])

In [107]:
a = lrg_array[:, 1::2]

In [108]:
a

array([[  2,   4,   7,   9,  12],
       [ 14,  17,  19,  22,  24],
       [ 27,  29,  32,  34,  37],
       [ 39,  42,  44,  47,  49],
       [ 52,  54,  57,  59,  62],
       [ 64,  67,  69,  72,  74],
       [ 77,  79,  82,  84,  87],
       [ 89,  92,  94,  97, 100]])

In [114]:
a[0] = 0

In [115]:
lrg_array[:, 1::2]

array([[  0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0],
       [ 27,  29,  32,  34,  37],
       [ 39,  42,  44,  47,  49],
       [ 52,  54,  57,  59,  62],
       [ 64,  67,  69,  72,  74],
       [ 77,  79,  82,  84,  87],
       [ 89,  92,  94,  97, 100]])

In [116]:
lrg_array[:, 1::2]

array([[  0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0],
       [ 27,  29,  32,  34,  37],
       [ 39,  42,  44,  47,  49],
       [ 52,  54,  57,  59,  62],
       [ 64,  67,  69,  72,  74],
       [ 77,  79,  82,  84,  87],
       [ 89,  92,  94,  97, 100]])

In [130]:
lrg_array

array([[  1,   0,   3,   0,   6,   0,   8,   0,  11,   0],
       [ 13,   0,  16,   0,  18,   0,  21,   0,  23,   0],
       [ 26,  27,  28,  29,  31,  32,  33,  34,  36,  37],
       [ 38,  39,  41,  42,  43,  44,  46,  47,  48,  49],
       [ 51,  52,  53,  54,  56,  57,  58,  59,  61,  62],
       [ 63,  64,  66,  67,  68,  69,  71,  72,  73,  74],
       [ 76,  77,  78,  79,  81,  82,  83,  84,  86,  87],
       [ 88,  89,  91,  92,  93,  94,  96,  97,  98, 100]])

In [131]:
lrg_array[lrg_array > 20]

array([ 21,  23,  26,  27,  28,  29,  31,  32,  33,  34,  36,  37,  38,
        39,  41,  42,  43,  44,  46,  47,  48,  49,  51,  52,  53,  54,
        56,  57,  58,  59,  61,  62,  63,  64,  66,  67,  68,  69,  71,
        72,  73,  74,  76,  77,  78,  79,  81,  82,  83,  84,  86,  87,
        88,  89,  91,  92,  93,  94,  96,  97,  98, 100])

In [132]:
lrg_array > 20

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True, False,  True,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])